# Generated by Django 5.2.4 on 2025-07-14 00:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=150, verbose_name="Tam Adı")),
                ("title", models.CharField(max_length=100, verbose_name="Unvan")),
                (
                    "photo",
                    models.ImageField(upload_to="team/", verbose_name="Fotoğraf"),
                ),
                (
                    "bio",
                    models.TextField(blank=True, null=True, verbose_name="Biyografi"),
                ),
                (
                    "linkedin_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="LinkedIn Profili"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Sitedeki sıralamayı belirler (küçükten büyüğe).",
                        verbose_name="Sıralama",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ekip Üyesi",
                "verbose_name_plural": "Ekip Üyeleri",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Başlık")),
                (
                    "slug",
                    models.SlugField(
                        editable=False, max_length=270, unique=True, verbose_name="Slug"
                    ),
                ),
                ("image", models.ImageField(upload_to="news/", verbose_name="Görsel")),
                ("summary", models.TextField(verbose_name="Özet")),
                ("content", models.TextField(verbose_name="İçerik")),
                (
                    "published_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Yayınlanma Tarihi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Haber/Makale",
                "verbose_name_plural": "Haberler/Makaleler",
                "ordering": ["-published_date"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Proje Adı")),
                ("description", models.TextField(verbose_name="Kısa Açıklama")),
                ("content", models.TextField(verbose_name="Detaylı İçerik")),
                (
                    "image",
                    models.ImageField(
                        upload_to="projects/", verbose_name="Proje Görseli"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        editable=False, max_length=220, unique=True, verbose_name="Slug"
                    ),
                ),
            ],
            options={
                "verbose_name": "Proje",
                "verbose_name_plural": "Projeler",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Hizmet Adı")),
                (
                    "description",
                    models.TextField(verbose_name="Kısa Açıklama (Anasayfa)"),
                ),
                (
                    "content",
                    models.TextField(
                        verbose_name="Detaylı İçerik (Hizmet Detay Sayfası)"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        help_text="Örn: 'fas fa-cogs' (Font Awesome ikon sınıfı)",
                        max_length=100,
                        verbose_name="İkon Sınıfı",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        editable=False, max_length=220, unique=True, verbose_name="Slug"
                    ),
                ),
            ],
            options={
                "verbose_name": "Hizmet",
                "verbose_name_plural": "Hizmetler",
            },
        ),
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="OneEye", max_length=100, verbose_name="Site Adı"
                    ),
                ),
                (
                    "about_us_title",
                    models.CharField(max_length=200, verbose_name="Hakkımızda Başlığı"),
                ),
                (
                    "about_us_content",
                    models.TextField(verbose_name="Hakkımızda İçeriği"),
                ),
                (
                    "team_section_title",
                    models.CharField(
                        default="Ekibimizle Tanışın",
                        max_length=200,
                        verbose_name="Ekip Bölümü Başlığı",
                    ),
                ),
                (
                    "contact_page_content",
                    models.TextField(verbose_name="İletişim Sayfası İçeriği"),
                ),
                (
                    "footer_text",
                    models.CharField(max_length=255, verbose_name="Footer Metni"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="İletişim E-posta"),
                ),
                (
                    "phone",
                    models.CharField(max_length=20, verbose_name="İletişim Telefon"),
                ),
                ("address", models.TextField(verbose_name="Adres")),
            ],
            options={
                "verbose_name": "Site Genel Ayarı",
                "verbose_name_plural": "Site Genel Ayarları",
            },
        ),
    ]
