# Generated by Django 5.2.4 on 2025-07-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Hizmet Başlığı"),
                ),
                ("short_description", models.TextField(verbose_name="Kısa Açıklama")),
                (
                    "cover_image",
                    models.ImageField(
                        upload_to="uploads/services/", verbose_name="Kapak Resmi"
                    ),
                ),
                ("detailed_content", models.TextField(verbose_name="Detaylı İçerik")),
                (
                    "slug",
                    models.SlugField(
                        max_length=200, unique=True, verbose_name="URL Adresi"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Sıralama"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Hizmet",
                "verbose_name_plural": "Hizmetler",
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_title",
                    models.CharField(
                        default="One Eye Systems",
                        max_length=200,
                        verbose_name="Site Başlığı",
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(
                        default="Teknoloji ile Geleceği Şekillendiriyoruz",
                        max_length=200,
                        verbose_name="Ana Sayfa Başlığı",
                    ),
                ),
                (
                    "hero_subtitle",
                    models.TextField(
                        default="Modern teknoloji çözümleri ile işletmenizi geleceğe taşıyoruz.",
                        verbose_name="Ana Sayfa Alt Başlığı",
                    ),
                ),
                (
                    "hero_background_image",
                    models.ImageField(
                        upload_to="uploads/site/",
                        verbose_name="Ana Sayfa Arkaplan Resmi",
                    ),
                ),
                (
                    "about_us_section_content",
                    models.TextField(
                        default="Biz One Eye Systems olarak, teknoloji dünyasında yenilikçi çözümler sunan bir ekibiz.",
                        verbose_name="Hakkımızda Bölümü İçeriği",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        default="info@oneeyesystems.com",
                        max_length=254,
                        verbose_name="İletişim E-posta",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        default="+90 212 123 45 67",
                        max_length=20,
                        verbose_name="Telefon Numarası",
                    ),
                ),
                (
                    "address",
                    models.TextField(default="İstanbul, Türkiye", verbose_name="Adres"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Konfigürasyonu",
                "verbose_name_plural": "Site Konfigürasyonu",
            },
        ),
    ]
