# Generated by Django 5.2.4 on 2025-07-14 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="bio_en",
            field=models.TextField(blank=True, null=True, verbose_name="Biyografi"),
        ),
        migrations.AddField(
            model_name="employee",
            name="bio_tr",
            field=models.TextField(blank=True, null=True, verbose_name="Biyografi"),
        ),
        migrations.AddField(
            model_name="employee",
            name="title_en",
            field=models.CharField(max_length=100, null=True, verbose_name="Unvan"),
        ),
        migrations.AddField(
            model_name="employee",
            name="title_tr",
            field=models.CharField(max_length=100, null=True, verbose_name="Unvan"),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="content_en",
            field=models.TextField(null=True, verbose_name="İçerik"),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="content_tr",
            field=models.TextField(null=True, verbose_name="İçerik"),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="summary_en",
            field=models.TextField(null=True, verbose_name="Özet"),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="summary_tr",
            field=models.TextField(null=True, verbose_name="Özet"),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="title_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Başlık"),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="title_tr",
            field=models.CharField(max_length=255, null=True, verbose_name="Başlık"),
        ),
        migrations.AddField(
            model_name="project",
            name="content_en",
            field=models.TextField(null=True, verbose_name="Detaylı İçerik"),
        ),
        migrations.AddField(
            model_name="project",
            name="content_tr",
            field=models.TextField(null=True, verbose_name="Detaylı İçerik"),
        ),
        migrations.AddField(
            model_name="project",
            name="description_en",
            field=models.TextField(null=True, verbose_name="Kısa Açıklama"),
        ),
        migrations.AddField(
            model_name="project",
            name="description_tr",
            field=models.TextField(null=True, verbose_name="Kısa Açıklama"),
        ),
        migrations.AddField(
            model_name="project",
            name="name_en",
            field=models.CharField(max_length=200, null=True, verbose_name="Proje Adı"),
        ),
        migrations.AddField(
            model_name="project",
            name="name_tr",
            field=models.CharField(max_length=200, null=True, verbose_name="Proje Adı"),
        ),
        migrations.AddField(
            model_name="service",
            name="content_en",
            field=models.TextField(
                null=True, verbose_name="Detaylı İçerik (Hizmet Detay Sayfası)"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="content_tr",
            field=models.TextField(
                null=True, verbose_name="Detaylı İçerik (Hizmet Detay Sayfası)"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="description_en",
            field=models.TextField(null=True, verbose_name="Kısa Açıklama (Anasayfa)"),
        ),
        migrations.AddField(
            model_name="service",
            name="description_tr",
            field=models.TextField(null=True, verbose_name="Kısa Açıklama (Anasayfa)"),
        ),
        migrations.AddField(
            model_name="service",
            name="name_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Hizmet Adı"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="name_tr",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Hizmet Adı"
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="about_us_content_en",
            field=models.TextField(null=True, verbose_name="Hakkımızda İçeriği"),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="about_us_content_tr",
            field=models.TextField(null=True, verbose_name="Hakkımızda İçeriği"),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="about_us_title_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Hakkımızda Başlığı"
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="about_us_title_tr",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Hakkımızda Başlığı"
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="contact_page_content_en",
            field=models.TextField(null=True, verbose_name="İletişim Sayfası İçeriği"),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="contact_page_content_tr",
            field=models.TextField(null=True, verbose_name="İletişim Sayfası İçeriği"),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="footer_text_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Footer Metni"
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="footer_text_tr",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Footer Metni"
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="team_section_title_en",
            field=models.CharField(
                default="Ekibimizle Tanışın",
                max_length=200,
                null=True,
                verbose_name="Ekip Bölümü Başlığı",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="team_section_title_tr",
            field=models.CharField(
                default="Ekibimizle Tanışın",
                max_length=200,
                null=True,
                verbose_name="Ekip Bölümü Başlığı",
            ),
        ),
    ]
