# Generated by Django 5.2.4 on 2025-07-13 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Proje Başlığı"),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        upload_to="projects/", verbose_name="Kapak Resmi"
                    ),
                ),
                ("short_description", models.TextField(verbose_name="Kısa Açıklama")),
                ("detailed_content", models.TextField(verbose_name="Detaylı İçerik")),
                (
                    "slug",
                    models.SlugField(
                        max_length=200, unique=True, verbose_name="URL Adresi"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Sıralama"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Proje",
                "verbose_name_plural": "Projeler",
                "ordering": ["order", "title"],
            },
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="about_us_section_content",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="hero_background_image",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="site_title",
        ),
        migrations.AddField(
            model_name="service",
            name="icon_class",
            field=models.CharField(
                blank=True,
                help_text="Örn: 'fa-solid fa-brain' (Font Awesome class'ı)",
                max_length=50,
                verbose_name="İkon Class",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="about_us_content",
            field=models.TextField(
                default="Biz One Eye Systems olarak, teknoloji dünyasında yenilikçi çözümler sunan bir ekibiz.",
                verbose_name="Hakkımızda İçeriği",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="about_us_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="site_images/",
                verbose_name="Hakkımızda Resmi",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="about_us_title",
            field=models.CharField(
                default="Biz Kimiz?", max_length=255, verbose_name="Hakkımızda Başlığı"
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="career_content",
            field=models.TextField(
                default="Ekibimize katılmak ister misiniz? CV'nizi gönderin!",
                help_text="Kariyer bölümünde görünecek açıklama metni.",
                verbose_name="Kariyer İçeriği",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="career_cv_email",
            field=models.EmailField(
                default="hr@oneeyesystems.com",
                max_length=254,
                verbose_name="CV E-posta Adresi",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="career_title",
            field=models.CharField(
                default="Kariyer", max_length=255, verbose_name="Kariyer Başlığı"
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="footer_description",
            field=models.TextField(
                default="One Eye Systems - Teknoloji ile geleceği şekillendiren çözümler.",
                help_text="Logo yanında görünecek kısa açıklama.",
                verbose_name="Footer Açıklaması",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="hero_video",
            field=models.FileField(
                blank=True,
                help_text="Ana sayfa arkaplan videosu. Yoksa, arkaplan rengi kullanılır.",
                null=True,
                upload_to="site_videos/",
                verbose_name="Hero Video",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="instagram_url",
            field=models.URLField(blank=True, verbose_name="Instagram URL"),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="linkedin_url",
            field=models.URLField(blank=True, verbose_name="LinkedIn URL"),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="twitter_url",
            field=models.URLField(blank=True, verbose_name="Twitter URL"),
        ),
        migrations.AlterField(
            model_name="service",
            name="cover_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="services/", verbose_name="Kapak Resmi"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Hizmet Başlığı"),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="hero_subtitle",
            field=models.CharField(
                default="Odaklanmak Başarının Anahtarıdır",
                max_length=500,
                verbose_name="Alt Başlık",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="hero_title",
            field=models.CharField(
                default="Tek Gözle Bakıyoruz, Çünkü...",
                max_length=255,
                verbose_name="Ana Başlık",
            ),
        ),
    ]
