# Generated by Django 5.2.4 on 2025-07-13 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_project_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={},
        ),
        migrations.AlterModelOptions(
            name="service",
            options={},
        ),
        migrations.AlterModelOptions(
            name="siteconfiguration",
            options={
                "verbose_name": "Site Configuration",
                "verbose_name_plural": "Site Configuration",
            },
        ),
        migrations.RemoveField(
            model_name="project",
            name="cover_image",
        ),
        migrations.RemoveField(
            model_name="project",
            name="detailed_content",
        ),
        migrations.RemoveField(
            model_name="project",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="project",
            name="order",
        ),
        migrations.RemoveField(
            model_name="project",
            name="short_description",
        ),
        migrations.RemoveField(
            model_name="project",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="project",
            name="title",
        ),
        migrations.RemoveField(
            model_name="service",
            name="cover_image",
        ),
        migrations.RemoveField(
            model_name="service",
            name="detailed_content",
        ),
        migrations.RemoveField(
            model_name="service",
            name="icon_class",
        ),
        migrations.RemoveField(
            model_name="service",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="service",
            name="order",
        ),
        migrations.RemoveField(
            model_name="service",
            name="short_description",
        ),
        migrations.RemoveField(
            model_name="service",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="service",
            name="title",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="about_us_content",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="about_us_image",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="about_us_title",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="address",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="career_content",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="career_cv_email",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="career_title",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="contact_email",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="footer_description",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="hero_subtitle",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="hero_title",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="hero_video",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="instagram_url",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="linkedin_url",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="twitter_url",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="project",
            name="content",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="project",
            name="content_en",
            field=models.TextField(default="", null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="content_tr",
            field=models.TextField(default="", null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="project",
            name="description_en",
            field=models.TextField(default="", null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="description_tr",
            field=models.TextField(default="", null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="projects/"),
        ),
        migrations.AddField(
            model_name="project",
            name="name",
            field=models.CharField(default="New Project", max_length=200),
        ),
        migrations.AddField(
            model_name="project",
            name="name_en",
            field=models.CharField(default="New Project", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="name_tr",
            field=models.CharField(default="New Project", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="content",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="service",
            name="content_en",
            field=models.TextField(default="", null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="content_tr",
            field=models.TextField(default="", null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="service",
            name="description_en",
            field=models.TextField(default="", null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="description_tr",
            field=models.TextField(default="", null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="icon",
            field=models.CharField(default="fa-solid fa-star", max_length=50),
        ),
        migrations.AddField(
            model_name="service",
            name="name",
            field=models.CharField(default="New Service", max_length=200),
        ),
        migrations.AddField(
            model_name="service",
            name="name_en",
            field=models.CharField(default="New Service", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="name_tr",
            field=models.CharField(default="New Service", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="about_us",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="about_us_en",
            field=models.TextField(default="", null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="about_us_tr",
            field=models.TextField(default="", null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="careers_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="contact_info",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="contact_info_en",
            field=models.TextField(default="", null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="contact_info_tr",
            field=models.TextField(default="", null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="site_description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="site_description_en",
            field=models.TextField(default="", null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="site_description_tr",
            field=models.TextField(default="", null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="site_title",
            field=models.CharField(default="One Eye Systems", max_length=200),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="site_title_en",
            field=models.CharField(
                default="One Eye Systems", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="site_title_tr",
            field=models.CharField(
                default="One Eye Systems", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="video_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
